### ISSUE TITLE
Google Maps does not load.

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/apcal#10]
When I want to create an event, Google Maps does not load.

modules/APCal/?event_id=0000000102&action=View&caldate=2017-3-16

**Comment by cesagonchu** [comment]
I still got this problem.

**Comment by mambax7** [comment]
This should be fixed now, but you have to add a Google Maps API in preferences

**Comment by cesagonchu** [comment]
Ok I will test with a new install.

**Comment by cesagonchu** [comment]
This is unfortunately not fixed.
In the preferences, we have to enter our own key, but when I look at the code, I do not see where the link is from our key to the files in the module.
You have pre-entered a key in **getCoords.html**, but I do not think this is the right method, otherwise, why should we enter our key in preferences?
This key is also called by the files (into /templates) **apcal_event_detail.tpl**(line 51) and **apcal_googlemap.tpl**(line40), with this script:
`<script async defer src="https://maps.googleapis.com/maps/api/js?key=<{$api_key}>&callback=initMap" type="text/javascript"></script>`

**Comment by cesagonchu** [comment]
Maybe can we use a non limited application like Openstreetmap?

http://wiki.openstreetmap.org/wiki/Main_Page

**Comment by mambax7** [comment]
Sorry, something went wrong  with the files. Let me fix it, and I'll upload it soon.

**Comment by mambax7** [comment]
I've uploaded the fixes to my repository. Please test...

**Comment by cesagonchu** [comment]
I downloaded your version:
https://github.com/mambax7/apcal/tree/c6f45a269bfc5a5a8f2b1a85eeff6a568f493e42

Now, I can't tell you if google map works or not, because, after setting permissions, there is no more button to submit an event.

This new error must first be solved:
https://github.com/XoopsModules25x/apcal/issues/25

**Comment by cesagonchu** [comment]
No button to submit event but I can submit when I click on a date inside the calendar.

So, Google map works when I want to enter cordinates for an event, but when I go to an event page detail (modules/apcal/?event_id=0000000001&action=View&caldate=2017-3-26) the map of google map doesn't show.

It seems that my key is not sended at the event page detail because on mouseover the map I can see this:
`https://maps.googleapis.com/maps/api/js?key=&callback=initMap`

Whereas when I am on the creation page of an event, I see that my key is displayed.

**Comment by ggoffy** [comment]
should be fixed with last version
